backend:
  name: github
  repo: mikelnorth/gatsbynetlify

media_folder: static/assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - {label: "Create At", name: "date", widget: "date", default: "blog"}
      - {label: "Post", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image", required: false}
